---
language: node_js
node_js:
  - 4
  - 6
  - 7

sudo: false

cache:
  yarn: true

before_install:
  - bash < <(curl -o- -L https://yarnpkg.com/install.sh)
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --no-lockfile

script:
  - yarn test

after_success:
  - |
    if [[ "$TRAVIS_NODE_VERSION" = "4" ]] ; then
      echo "Pushing to Coveralls..." >&2
      yarn coveralls
    else
      echo "Not pushing to Coveralls."
    fi
